sc:
  local:
    enabled: true
    default: true
    provisioner_image: |
      {{ .dockerio_registry }}/openebs/provisioner-localpv:3.3.0
    linux_utils_image: |
      {{ .dockerio_registry }}/openebs/linux-utils:3.3.0
    path: /var/openebs/local
  nfs: # each k8s_cluster node should install nfs-utils
    enabled: false
    default: false
    server: |
      {{ groups.nfs | first }}
    path: /share/kubernetes
