# global_registry for all image
global_registry: ""
# dockerio_registry for docker.io image.
dockerio_registry: |
  {{- if ne .global_registry "" -}}
  {{ .global_registry }}
  {{- else -}}
  docker.io
  {{- end -}}
# quayio_registry for quay.io image.
quayio_registry: |
  {{- if ne .global_registry "" -}}
  {{ .global_registry }}
  {{- else -}}
  quay.io
  {{- end -}}
# ghcrio_registry for ghcr.io image.
ghcrio_registry: |
  {{- if ne .global_registry "" -}}
  {{ .global_registry }}
  {{- else -}}
  ghcr.io
  {{- end -}}
# k8s_registry for registry.k8s.io image.
k8s_registry: |
  {{- if ne .global_registry "" -}}
  {{ .global_registry }}
  {{- else -}}
  registry.k8s.io
  {{- end -}}

security_enhancement: false

kubernetes:
  etcd:
    # It is possible to deploy etcd with three methods.
    # external: Deploy etcd cluster with external etcd cluster.
    # internal: Deploy etcd cluster by static pod.
    deployment_type: external
cri:
  # support: containerd,docker
  container_manager: docker