# permissions for end users to edit kubeadmconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeadmconfig-editor-role
rules:
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - kubeadmconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - kubeadmconfigs/status
  verbs:
  - get
