# permissions for end users to view registries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registry-viewer-role
rules:
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - registries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubekey.kubesphere.io
  resources:
  - registries/status
  verbs:
  - get
