apiVersion: kubekey.kubesphere.io/v1
kind: Config
metadata:
  name: example
spec:
  # zone for kk. how to download files
#  kkzone: cn
  # work_dir is the directory where the artifact is extracted.
#  work_dir: /var/lib/kubekey/
  # cni binary
  cni_version: v1.2.0
  # helm binary
  helm_version: v3.14.2
  # docker-compose binary
  dockercompose_version: v2.24.6
  # harbor image tag
  harbor_version: v2.10.1
  # registry image tag
  registry_version: 2.8.3
  # keepalived image tag
  keepalived_version: stable
  # runc binary
  runc_version: v1.1.11
  # calicoctl binary
  calico_version: v3.27.2
  # etcd binary
  etcd_version: v3.5.6
  # crictl binary
  crictl_version: v1.29.0
  # cilium helm
  cilium_version: 1.15.4
  # kubeovn helm
  kubeovn_version: 0.1.0
  # hybridnet helm
  hybridnet_version: 0.6.8
  # containerd binary
  containerd_version: v1.7.0
  # docker binary
  docker_version: 24.0.6
  # cridockerd
  cridockerd_version: v0.3.10
  # the version of kubernetes to be installed.
  # should be greater than or equal to kube_version_min_required.
  kube_version: v1.23.15
  # nfs provisioner helm version
  nfs_provisioner_version: 4.0.18
  # oras binary
  oras_version: v1.1.0
