cri:
  # support: systemd, cgroupfs
  cgroup_driver: systemd
  sandbox_image_tag: 3.5
  # support: containerd,docker,crio
  # the endpoint of containerd
  cri_socket: |
    {{- if .cri.container_manager | eq "containerd" }}
    unix:///var/run/containerd/containerd.sock
    {{- else if and (.cri.container_manager | eq "docker") (.kube_version | semverCompare ">=v1.24.0") }}
    unix:///var/run/cri-dockerd.sock
    {{- else if and (.cri.container_manager | eq "docker") (.kube_version | semverCompare "<v1.24.0") }}
    unix:///var/run/docker.sock
    {{- end }}
  containerd:
    data_root: /var/lib/containerd
  docker:
    data_root: /var/lib/docker
  registry:
    mirrors: ["https://registry-1.docker.io"]
    insecure_registries: []
    auths: []