---
- name: Sync etcd ca file to remote
  tags: ["certs"]
  copy:
    src: |
      {{ .binary_dir }}/pki/root.crt
    dest: /etc/kubernetes/pki/etcd/ca.crt
    mode: 0755
- name: Sync etcd cert files to remote
  tags: ["certs"]
  copy:
    src: |
      {{ .binary_dir }}/pki/etcd.crt
    dest: /etc/kubernetes/pki/etcd/client.crt
    mode: 0755
- name: Sync etcd key files to remote
  tags: ["certs"]
  copy:
    src: |
      {{ .binary_dir }}/pki/etcd.key
    dest: /etc/kubernetes/pki/etcd/client.key
    mode: 0755
