---
# install crictl
- include_tasks: install_crictl.yaml

# install docker
- include_tasks: install_docker.yaml
  when: .cri.container_manager | eq "docker"

    # install containerd
- include_tasks: install_containerd.yaml
  when: .cri.container_manager | eq "containerd"

# install cridockerd
- include_tasks: install_cridockerd.yaml
  when:
  - .cri.container_manager | eq  "docker"
  - .kube_version | versionAtLeast "v1.24.0"


