cri:
  # Container runtime to use. Supported: containerd, docker
  container_manager: containerd
  # Cgroup driver for the container runtime. Supported: systemd, cgroupfs
  cgroup_driver: systemd
    # tag: "3.9"
  # CRI socket endpoint for the selected container runtime
  cri_socket: >-
    {{- if .cri.container_manager | eq "containerd" -}}
    unix:///var/run/containerd/containerd.sock
    {{- else if and (.cri.container_manager | eq "docker") (.kubernetes.kube_version | semverCompare ">=v1.24.0") -}}
    unix:///var/run/cri-dockerd.sock
    {{- end -}}

  # Registry configuration for CRI, including mirrors, insecure registries, and authentication
  registry:
    mirrors: ["https://registry-1.docker.io"]
    insecure_registries: []
    auths: []
    
  # skip tls verify when pulling images
  skip_tls_verify: false
