kubernetes:
  # helm binary
  helm_version: v3.12.1
  control_plane_endpoint:
    kube_vip:
      image:
        tag: v0.7.2
    haproxy:
      image:
        tag: 2.9.6-alpine
etcd:
  # etcd binary
  etcd_version: v3.5.9
image_registry:
  # ========== image registry ==========
  # keepalived image tag. Used for load balancing when there are multiple image registry nodes.
  keepalived_version: 2.0.20
  # ========== image registry: harbor ==========
  # harbor image tag
  harbor_version: v2.10.2
  # docker-compose binary
  dockercompose_version: v2.20.3
  # ========== image registry: docker-registry ==========
  # docker-registry image tag
  docker_registry_version: 2.8.3
cri:
  # support: containerd,docker
  container_manager: containerd
  sandbox_image:
    tag: "3.7"
  # ========== cri ==========
  # crictl binary
  crictl_version: v1.27.0
  # ========== cri: docker ==========
  # docker binary
  docker_version: 24.0.9
  # cridockerd. Required when kube_version is greater than 1.24
  cridockerd_version: v0.3.15
  # ========== cri: containerd ==========
  # containerd binary
  containerd_version: v1.7.13
  # runc binary
  runc_version: v1.1.12
cni:
  multus:
    image:
      tag: v4.0.2
  # ========== cni ==========
  # cni_plugins binary (optional)
  # cni_plugins_version: v1.2.0
  # ========== cni: calico ==========
  # calicoctl binary
  calico_version: v3.28.5
  # ========== cni: cilium ==========
  # cilium helm
  cilium_version: 1.16.18
  # ========== cni: flannel ==========
  flannel_version: v0.27.4
  # ========== cni: kubeovn ==========
  # kubeovn helm
  kubeovn_version: v1.13.15
  # ========== cni: hybridnet ==========
  # hybridnet helm
  hybridnet_version: 0.6.8
storage_class:
  # ========== storageclass ==========
  # ========== storageclass: local ==========
  # openebs/dynamic-localpv-provisioner helm chart version.
  localpv_provisioner_version: 4.4.0
  # ========== storageclass: nfs ==========
  # nfs provisioner helm version
  nfs_provisioner_version: 4.0.18
dns:
  dns_image:
    tag: v1.10.1
  dns_cache_image:
    tag: 1.22.20
image_manifests:
  # calico for v3.28.5
  - quay.io/tigera/operator:v1.34.13
  - docker.io/calico/apiserver:v3.28.5
  - docker.io/calico/cni:v3.28.5
  - docker.io/calico/ctl:v3.28.5
  - docker.io/calico/csi:v3.28.5
  - docker.io/calico/kube-controllers:v3.28.5
  - docker.io/calico/node-driver-registrar:v3.28.5
  - docker.io/calico/node:v3.28.5
  - docker.io/calico/pod2daemon-flexvol:v3.28.5
  - docker.io/calico/typha:v3.28.5
  # dns
  - docker.io/kubesphere/coredns:v1.10.1
  - docker.io/kubesphere/k8s-dns-node-cache:1.22.20
  # kubernetes
  - docker.io/kubesphere/kube-apiserver:{{ .kubernetes.kube_version }}
  - docker.io/kubesphere/kube-controller-manager:{{ .kubernetes.kube_version }}
  - docker.io/kubesphere/kube-proxy:{{ .kubernetes.kube_version }}
  - docker.io/kubesphere/kube-scheduler:{{ .kubernetes.kube_version }}
  - docker.io/kubesphere/pause:3.7
  # openebs/local for 4.4.0
  - docker.io/openebs/linux-utils:4.3.0
  - docker.io/openebs/provisioner-localpv:4.3.0
  # control_plane_endpoint ha
  - docker.io/library/haproxy:2.9.6-alpine
  - docker.io/plndr/kube-vip:v0.7.2