kubernetes:
  # helm binary
  helm_version: v3.8.2
etcd:
  # etcd binary
  etcd_version: v3.5.4
image_registry:
  type: harbor
  # keepalived image tag. Used for load balancing when there are multiple image registry nodes.
  keepalived_version: 2.0.20
  # ========== image registry: harbor ==========
  # harbor image tag
  harbor_version: v2.6.3
  # docker-compose binary
  dockercompose_version: v2.12.2
  # ========== image registry: docker-registry ==========
  # docker-registry image tag
  docker_registry_version: 2.8.3
cri:
  # support: containerd,docker
  container_manager: docker
  sandbox_image:
    tag: "3.6"
  # ========== cri ==========
  # crictl binary
  crictl_version: v1.23.0
  # ========== cri: docker ==========
  # docker binary
  docker_version: 20.10.18
  # cridockerd. Required when kube_version is greater than 1.24
  cridockerd_version: v0.3.10
  # ========== cri: containerd ==========
  # containerd binary
  containerd_version: v1.6.8
  # runc binary
  runc_version: v1.1.4
cni:
  multus:
    image:
      tag: v3.9.3
  # ========== cni ==========
  # cni_plugins binary (optional)
  # cni_plugins_version: v1.1.1
  # ========== cni: calico ==========
  # calicoctl binary
  calico_version: v3.24.5
  # ========== cni: cilium ==========
  # cilium helm
  cilium_version: 1.14.19
  # ========== cni: kubeovn ==========
  # kubeovn helm
  kubeovn_version: 1.10.0
  # ========== cni: hybridnet ==========
  # hybridnet helm
  hybridnet_version: 0.6.8
storage_class:
  # ========== storageclass ==========
  # ========== storageclass: local ==========
  local:
    provisioner_image:
      tag: 3.3.0
    linux_utils_image:
      tag: 3.3.0
  # ========== storageclass: nfs ==========
  # nfs provisioner helm version
  nfs_provisioner_version: 4.0.2
dns:
  dns_image:
    tag: v1.8.6
  dns_cache_image:
    tag: 1.21.1
image_manifests:
  - docker.io/calico/apiserver:v3.24.5
  - docker.io/calico/cni:v3.24.5
  - docker.io/calico/ctl:v3.24.5
  - docker.io/calico/csi:v3.24.5
  - docker.io/calico/kube-controllers:v3.24.5
  - docker.io/calico/node-driver-registrar:v3.24.5
  - docker.io/calico/node:v3.24.5
  - docker.io/calico/pod2daemon-flexvol:v3.24.5
  - docker.io/calico/typha:v3.24.5
  - docker.io/kubesphere/coredns:v1.8.6
  - docker.io/kubesphere/k8s-dns-node-cache:1.21.1
  - docker.io/kubesphere/kube-apiserver:{{ .kubernetes.kube_version }}
  - docker.io/kubesphere/kube-controller-manager:{{ .kubernetes.kube_version }}
  - docker.io/kubesphere/kube-proxy:{{ .kubernetes.kube_version }}
  - docker.io/kubesphere/kube-scheduler:{{ .kubernetes.kube_version }}
  - docker.io/kubesphere/pause:3.6
  - docker.io/openebs/linux-utils:3.3.0
  - docker.io/openebs/provisioner-localpv:3.3.0
  - quay.io/tigera/operator:v1.28.5
