kubernetes:
  # helm binary
  helm_version: v3.8.2
  sandbox_image:
    tag: "3.6"
  control_plane_endpoint:
    kube_vip:
      image:
        tag: v0.7.2
    haproxy:
      image:
        tag: 2.9.6-alpine
etcd:
  # etcd binary
  etcd_version: v3.5.6
image_registry:
  # keepalived image tag. Used for load balancing when there are multiple image registry nodes.
  keepalived_version: 2.0.20
  # ========== image registry: harbor ==========
  # Harbor image tag (only valid if type is harbor).
  harbor_version: v2.10.2
  # docker-compose binary
  dockercompose_version: v2.20.3
  # ========== image registry: docker-registry ==========
  # docker-registry image tag
  docker_registry_version: 2.8.3
cri:
  # support: containerd,docker
  container_manager: docker
  # ========== cri ==========
  # crictl binary
  crictl_version: v1.23.0
  # ========== cri: docker ==========
  # docker binary
  docker_version: 20.10.24
  # cridockerd. Required when kube_version is greater than 1.24
  cridockerd_version: v0.3.2
  # ========== cri: containerd ==========
  # containerd binary
  containerd_version: v1.6.20
  # runc binary
  runc_version: v1.1.5
cni:
  multus:
    image:
      tag: v3.9.3
  # ========== cni ==========
  # cni_plugins binary (optional)
  # cni_plugins_version: v1.1.1
  # ========== cni: calico ==========
  # calicoctl binary
  calico_version: v3.25.2
  # ========== cni: cilium ==========
  # cilium helm
  cilium_version: 1.14.19
  # ========== cni: flannel ==========
  flannel_version: v0.27.4
  # ========== cni: kubeovn ==========
  # kubeovn helm
  kubeovn_version: v1.13.15
  # ========== cni: hybridnet ==========
  # hybridnet helm
  hybridnet_version: 0.6.8
storage_class:
  # ========== storageclass ==========
  # ========== storageclass: local ==========
  # openebs/dynamic-localpv-provisioner helm chart version.
  localpv_provisioner_version: 4.4.0
  # ========== storageclass: nfs ==========
  # nfs provisioner helm version
  nfs_provisioner_version: 4.0.18
dns:
  dns_image:
    tag: v1.8.6
  dns_cache_image:
    tag: 1.21.1
image_manifests:
  # calico for v3.25.2
  - quay.io/tigera/operator:v1.29.6
  - docker.io/calico/apiserver:v3.25.2
  - docker.io/calico/cni:v3.25.2
  - docker.io/calico/ctl:v3.25.2
  - docker.io/calico/csi:v3.25.2
  - docker.io/calico/kube-controllers:v3.25.2
  - docker.io/calico/node-driver-registrar:v3.25.2
  - docker.io/calico/node:v3.25.2
  - docker.io/calico/pod2daemon-flexvol:v3.25.2
  - docker.io/calico/typha:v3.25.2
  # dns
  - registry.k8s.io/coredns/coredns:v1.8.6
  - registry.k8s.io/dns/k8s-dns-node-cache:1.21.1
  # kubernetes
  - registry.k8s.io/kube-apiserver:{{ .kubernetes.kube_version }}
  - registry.k8s.io/kube-controller-manager:{{ .kubernetes.kube_version }}
  - registry.k8s.io/kube-proxy:{{ .kubernetes.kube_version }}
  - registry.k8s.io/kube-scheduler:{{ .kubernetes.kube_version }}
  - registry.k8s.io/pause:3.6
  # openebs/local for 4.4.0
  - docker.io/openebs/linux-utils:4.3.0
  - docker.io/openebs/provisioner-localpv:4.4.0
  # control_plane_endpoint ha
  - docker.io/library/haproxy:2.9.6-alpine
  - docker.io/plndr/kube-vip:v0.7.2
