kubernetes:
  # helm binary
  helm_version: v3.13.3
etcd:
  # etcd binary
  etcd_version: v3.5.10
image_registry:
  # ========== image registry ==========
  # keepalived image tag. Used for load balancing when there are multiple image registry nodes.
  keepalived_version: 2.0.20
  # ========== image registry: harbor ==========
  # harbor image tag
  harbor_version: v2.10.1
  # docker-compose binary
  dockercompose_version: v2.20.3
  # ========== image registry: docker-registry ==========
  # docker-registry image tag
  docker_registry_version: 2.8.3
cri:
  # support: containerd,docker
  container_manager: containerd
  sandbox_image:
    tag: "3.8"
  # ========== cri ==========
  # crictl binary
  crictl_version: v1.30.0
  # ========== cri: docker ==========
  # docker binary
  docker_version: 24.0.7
  # cridockerd. Required when kube_version is greater than 1.24
  cridockerd_version: v0.3.1
  # ========== cri: containerd ==========
  # containerd binary
  containerd_version: v1.7.6
  # runc binary
  runc_version: v1.1.7
cni:
  multus:
    image:
      tag: v4.2.1
  # ========== cni ==========
  # cni_plugins binary (optional)
  # cni_plugins_version: v1.2.0
  # ========== cni: calico ==========
  # calicoctl binary
  calico_version: v3.28.2
  # ========== cni: cilium ==========
  # cilium helm
  cilium_version: 1.15.4
  # ========== cni: kubeovn ==========
  # kubeovn helm
  kubeovn_version: 1.13.0
  # ========== cni: hybridnet ==========
  # hybridnet helm
  hybridnet_version: 0.6.8
storage_class:
  # ========== storageclass ==========
  # ========== storageclass: local ==========
  local:
    provisioner_image:
      tag: 4.0.0
    linux_utils_image:
      tag: 4.0.0
  # ========== storageclass: nfs ==========
  # nfs provisioner helm version
  nfs_provisioner_version: 4.1.0
dns:
  dns_image:
    tag: v1.11.1
  dns_cache_image:
    tag: 1.23.1
image_manifests:
- docker.io/calico/apiserver:v3.28.2
- docker.io/calico/cni:v3.28.2
- docker.io/calico/csi:v3.28.2
- docker.io/calico/kube-controllers:v3.28.2
- docker.io/calico/node-driver-registrar:v3.28.2
- docker.io/calico/node:v3.28.2
- docker.io/calico/pod2daemon-flexvol:v3.28.2
- docker.io/kubesphere/k8s-dns-node-cache:1.23.1
- docker.io/openebs/provisioner-localpv:4.0.0
- docker.io/openebs/linux-utils:4.0.0
- docker.io/kubesphere/coredns:v1.11.1
- docker.io/kubesphere/kube-apiserver:{{ .kube_version }}
- docker.io/kubesphere/kube-controller-manager:{{ .kube_version }}
- docker.io/kubesphere/kube-proxy:{{ .kube_version }}
- docker.io/kubesphere/kube-scheduler:{{ .kube_version }}
- docker.io/kubesphere/pause:3.8
- quay.io/tigera/operator:v1.34.5
- docker.io/calico/ctl:v3.28.2
- docker.io/calico/typha:v3.28.2
- docker.io/calico/apiserver:v3.28.2
- docker.io/calico/kube-controllers:v3.28.2
- docker.io/calico/node:v3.28.2
- docker.io/calico/pod2daemon-flexvol:v3.28.2
- docker.io/calico/cni:v3.28.2
- docker.io/calico/node-driver-registrar:v3.28.2
- docker.io/calico/csi:v3.28.2
