version: '3.8'

# Docker-Compose 单容器使用参考 YAML 配置文件
# 更多配置参数请参考镜像 README.md 文档中说明
services:
  keepalived:
    image: 'registry.cn-shenzhen.aliyuncs.com/colovu/keepalived:2.1'
    privileged: true
    network_mode: host
    volumes:
      - ./keepalived-backup.conf:/srv/conf/keepalived/keepalived.conf
      - ./check_harbor.sh:/srv/conf/keepalived/check_harbor.sh
    container_name: keepalived
    restart: on-failure
