---
- name: Stop cri-dockerd service
  ignore_errors: true
  command: |
    systemctl stop cri-dockerd.service
    systemctl disable cri-dockerd.service
    rm -rf /etc/systemd/system/cri-dockerd.service*
    systemctl daemon-reload
    systemctl reset-failed cri-dockerd.service

- name: Delete cri-dockerd residue files
  command: |
    rm -rf /etc/cri-dockerd
    rm -f /usr/local/bin/cri-dockerd