- hosts:
    - localhost
  roles:
    - init/init-artifact
  tasks:
    - name: Package image
      image:
        pull: "{{ .image_manifests | toJson }}"
      when: .image_manifests | default list | len | lt 0
    - name: Export artifact
      command: |
        cd {{ .work_dir }}/kubekey && tar -czvf ../kubekey-artifact.tar.gz *
