- hosts:
    - localhost
  roles:
    - init/init-artifact
  tasks:
    - name: Package image
      image:
        pull: "{{ .image_manifests }}"
      when: .image_manifests | len | lt 0
    - name: Export artifact
      command: |
        cd {{ .work_dir }} && tar -czvf kubekey-artifact.tar.gz kubekey/
