name: BuildReleaser

on:
  push:
    tags:
      - 'v4*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    if: github.repository == 'kubesphere/kubekey'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prepare
        id: prepare
        run: |
          LDFLAGS=$(bash hack/version.sh)
          VERSION=latest
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          fi

          echo "ldflags=${LDFLAGS}" >> "$GITHUB_OUTPUT"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.3

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: v2.5.1
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LDFLAGS: ${{ steps.prepare.outputs.ldflags }}

      - name: Upload Extra File
        run: |
          TAG=${{ steps.prepare.outputs.version }}
          if [[ $tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            REGISTRY=docker.io/kubesphere TAG=$tag make generate
          else
            REGISTRY=docker.io/kubespheredev TAG=$tag make generate
          fi
          gh release upload "$TAG" config/capkk/release/* --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}