renew_certs:
  enabled: false
  is_docker: |
    {{- if .cri.container_manager | eq "docker" -}}
    true
    {{- else -}}
    false
    {{- end -}}
  is_kubeadm_alpha: |
    {{- if .kube_version | semverCompare "<v1.20.0" -}}
    true
    {{- else -}}
    false
    {{- end -}}
